language: node_js
node_js: node
branches:
  only: master
install:
- npm install
before_script:
- echo -e "Host $HOST\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
script: npm run publish
before_deploy:
- cd dist
deploy:
  skip_cleanup: true
  provider: npm
  email: asmodeusxi@gmail.com
  on:
    branch: master
  api_key:
    secure: JD+0p3LTn/7+8a79ME6ZMKDmjIxoVmcczgye+vCrzg3dfzZaJlBXUjmA9ZsyrKVQDi2SshwLWxFXMYszYifp7hpPihci+45ogSXDHhHR8upXMfXJBh6ZQeXfN9cU2rGZUYFLejlFw+/vUeVt99ONrU6DcLUuucoPsa7sw4EtXbkghT/F6sSVXLy0EVvQz6s13J4XfWCGgocm6aJSJj1dqsjll89dRQsI6tUQtYoWL/iQa1zwIPsilnW9AreM9RzN3IGCfo6iJWhe5bvR9PGighK0ObPUfE360qh0Zhh28AoHa+rdr8RngIk4Ep41KDsYJ5u0Bb/jLKxnp820SlfkLboJMuohAERJIonKRao2+CtSZQX69ltVKPn7NK1W0yT+N4pZB15mkNMkwyYBxlySb+f/q3WBdrYNJzwDB7gBpfZX0iPRIUBWu/4PhI27U5ctVG/qd5Y/T1wfwOBLHs8SJf+1Xu5f7hL9f4mvOmtZtL5yR+MGyr67I3ssmj7vyZ87N7N+N/dKfFqtmN+l9YF6MgwKgdWPHtU2TIkAEdoAqZGOCwQa0rEEIXZOa8mdek5JuYXWIFwyEj8wm3tS67kO53CxElTd+KvFTp14gtCZb9dc4Z5mFbmngCYPL3TowB8jdL91DZe6CIY/2rgGsn2NKpA4nMQ8VOA4cwYvxRp4QZU=
