language: node_js
node_js: node
branches:
  only: master
install:
- npm install
before_script:
- echo -e "Host $HOST\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
script: npm run publish
before_deploy:
- cd dist
deploy:
  skip_cleanup: true
  provider: npm
  email: asmodeusxi@gmail.com
  on:
    branch: master
  api_key:
    secure: WIfHYbNahUOEEhBDEaNrTFd68CQitH707UCCho8LkyFPzxrcgxTs2NkPyodKM8BM480edZmqKrkkrb08D1yIbjgShdd0QrSSuNRL6fENo02BcTJIzbFg/RMP8FHsuIYsxyUnoD6/O8XhpgPX9bXEuUBiFAVwsU3XMtxSxPBs8n2yyBBSvdeorZOvGTn6F95ajgvG8QLbZJTMkzItQpJNl+u6KmnnnN29+lAcOUOBqIR00X/embRStImqi8fJaV3EfCtVyL5hdQQSRBzJTgafrgmEzuA7kmj/ouMN+bmh/gTsqnRDA+kjA/vbaVkRWPXXYRqYk8jvouipp0oMc+ZQxnoJ8d4Os1BlxqFFVbm9WKPFdVuny0vBR6IK77JnOO78dPJQF4cquWX8emPJS3yfAgM9DQmbYtCs25GDMiciNlhOPQmhGpzYq6/q351EDvygxuBA3XTTpRGPoYY1+lU4b0cQ+MQfR6mbIzbm2XpRKDOwoV0WCOvzybhDzZ9Qzux58Zu3q1eSaISjduAM2cEb5LbAoGUHcR+dqz+SH1HGiVKB8N1ggxCo/r17hAdj7iCH5GfhaIavfBfKCIi3cei27sBZIOEJCFDOprhSu4xcMSAHYcW+PkDBFs3+d43FK7uoJqnz8ze6424LRF2jaRqibmce6N6wVXe1Enf9T1U8dA8=
